### ISSUE TITLE
Contact - Location pin is missing from map

### ISSUE THREAD

**Issue by ianfader** [CCI-Studios/Otools-2015#72] opened 2017-05-26 13:53 UTC
![screen shot 2017-05-26 at 9 51 32 am](https://cloud.githubusercontent.com/assets/8989188/26497332/214c6bee-41f9-11e7-9798-ac03488644c5.png)

**Comment by ccmorris** [comment] 2018-05-15 14:44
@tgascoigne14 cannot reproduce this issue. there was another problem with this map since the staging site has a redirect to www.otools.ccistaging.com now. that may have fixed this? I'm going to close this and you can reopen it if there is a problem.

**Closed as completed by ccmorris** 2018-05-15 14:44 UTC
